# Generated by Django 3.2.5 on 2021-07-20 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='photo1',
            field=models.ImageField(blank=True, null=True, upload_to='book_images/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='book',
            name='photo2',
            field=models.ImageField(blank=True, null=True, upload_to='book_images/%Y/%m/%d/'),
        ),
    ]
