# Generated by Django 3.2.5 on 2021-07-20 14:46

from django.db import migrations
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20210720_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='location',
            field=location_field.models.plain.PlainLocationField(max_length=63, null=True),
        ),
    ]
